/* -*- C++ -*- */
/* Generated by opendds_idl version 3.29.1 (ACE version 6.5.21) running on input file C:\Dev\OpenDDS-Standalone\IsolatedEnv\idl\Person\Person.idl */
#ifndef OPENDDS_IDL_GENERATED_PERSONTYPESUPPORTIMPL_H_RKDJWI
#define OPENDDS_IDL_GENERATED_PERSONTYPESUPPORTIMPL_H_RKDJWI

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 29, 1)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "PersonC.h"
#include "PersonTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Identity */



/* Begin STRUCT: Person */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct Identity_Person_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<Identity_Person_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<Identity_Person_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::Identity::Person& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::Identity::Person>& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const KeyOnly< ::Identity::Person>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::Identity::Person& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::Identity::Person>& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const KeyOnly<const  ::Identity::Person>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::Identity::Person& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::Identity::Person& stru);

bool operator<<(Serializer& strm, const ::Identity::Person& stru);

bool operator>>(Serializer& strm,  ::Identity::Person& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::Identity::Person>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::Identity::Person>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::Identity::Person>& stru);

void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const ::Identity::Person>& stru);

bool operator<<(Serializer& strm, const KeyOnly<const ::Identity::Person>& stru);

bool operator>>(Serializer& strm, const KeyOnly< ::Identity::Person>& stru);

template <>
struct MarshalTraits< ::Identity::Person> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::Identity::Person&) { return false; }
  static bool from_message_block( ::Identity::Person&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace Identity {
/// This structure supports use of std::map with one or more keys.
struct  Person_OpenDDS_KeyLessThan {
  bool operator()(const  ::Identity::Person& v1, const  ::Identity::Person& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.uid < v2.uid) return true;
    if (v2.uid < v1.uid) return false;
    return false;
  }
};
}

namespace Identity {
class PersonTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::Identity::Person> {
  typedef  ::Identity::Person MessageType;
  typedef  ::Identity::PersonSeq MessageSequenceType;
  typedef  ::Identity::PersonSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::Identity::PersonTypeSupport TypeSupportType;
  typedef  ::Identity::PersonTypeSupportImpl TypeSupportImplType;
  typedef  ::Identity::PersonDataWriter DataWriterType;
  typedef  ::Identity::PersonDataReader DataReaderType;
  typedef  ::Identity::Person_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::Identity::Person> KeyOnlyType;
  typedef OpenDDS::DCPS::Identity_Person_xtag XtagType;

  static const char* type_name() { return "Identity::Person"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace Identity {
class  PersonTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<Person>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<Person>
{
public:
  typedef PersonTypeSupport TypeSupportType;
  typedef PersonTypeSupport::_var_type _var_type;
  typedef PersonTypeSupport::_ptr_type _ptr_type;

  PersonTypeSupportImpl() {}
  virtual ~PersonTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  Person* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const Person& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const Person& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, Person_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, Person_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static PersonTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::Identity::Person>();
bool gen_skip_over(Serializer& ser,  ::Identity::Person*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Identity::Person,  ::Identity::Person>(DDS::DynamicType_ptr type, const  ::Identity::Person& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::Identity::Person,  ::Identity::Person>(DDS::DynamicType_ptr type,  ::Identity::Person& value);

template <>
const  ::Identity::Person* get_dynamic_data_adapter_value< ::Identity::Person,  ::Identity::Person>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: Person */

/* End MODULE: Identity */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_PERSONTYPESUPPORTIMPL_H_RKDJWI */
